
create table if not exists orders(
	id int(32) auto_increment not null primary key,
	seller_nick varchar(900) not null default "unknow" comment "卖家昵称",
	buyer_nick varchar(300) not null default "unknow" comment "买家昵称",
	ouid varchar(300) not null default "unknow" comment "crm ouid",
	title varchar(900) not null default "unknow" comment "交易标题",
	type varchar(100) not null default "unknow" comment "交易类型",
	created datetime not null default "0000-00-00 00:00:00" comment "交易创建时间",
	port char(10) not null default "unknow" comment "销售平台",
	tid bigint(30) not null default 000000 comment "交易编号",
	shipping_company_name varchar(300) not null default "unknow" comment "物流公司",
	sid varchar(300) not null default "000000" comment "物流运单号",
	seller_rate char(10) not null default "unknow" comment "卖家是否已评价",
	buyer_rate char(10) not null default "unknow" comment "买家是否已评价",
	status varchar(300) not null default "unknow" comment "交易状态",
	payment decimal(9,2) not null default -1.00 comment "支付金额",
	pay_way varchar(300) not null default "unknow" comment "支付方式",
	discount_fee decimal(9,2) not null default -1.00 comment "子订单级订单优惠金额",
	adjust_fee decimal(9,2) not null default -1.00 comment "手工调整金额",
	post_fee decimal(9,2) not null default -1.00 comment "邮费",
	total_fee decimal(9,2) not null default -1.00 comment "商品金额",
	pay_time datetime not null default "0000-00-00 00:00:00" comment "付款时间",
	end_time datetime not null default "0000-00-00 00:00:00" comment "交易结束时间",
	modified datetime not null default "0000-00-00 00:00:00" comment "交易修改时间",
	consign_time datetime not null default "0000-00-00 00:00:00" comment "卖家发货时间",
	received_payment decimal(9,2) not null default -1.00 comment "卖家实际收到支付宝打款金额",
	commission_fee decimal(9,2) not null default -1.00 comment "交易佣金",
	alipay_no varchar(300) not null default "000000" comment "支付宝交易号",
	alipay_id bigint(30) not null default 000000 comment "买家的支付宝id号",
	buyer_area varchar(100) not null default "unknow" comment "买家下单地区",
	pic_path varchar(100) not null default "unknow" comment "商品图片绝对途径",
	num_iid varchar(100) not null default "000000" comment "商品数字编号",
	price decimal(9,2) not null default -1.00 comment "商品价格",
	shipping_type varchar(100) not null default "unknow" comment "创建交易时的物流方式",
	num int not null default 0 comment "商品购买数量",
	point_fee int not null default -1 comment "买家使用积分",
	real_point_fee int not null default -1 comment "买家实际使用积分",
	buyer_obtain_point_fee int not null default -1 comment "买家获得积分",
	receiver_name varchar(300) not null default "unknow" comment "收货人的姓名",
	receiver_country varchar(100) not null default "unknow" comment "收货人的国籍",
	receiver_state varchar(100) not null default "unknow" comment "收货人所在省份",
	receiver_city varchar(100) not null default "unknow" comment "收货人的所在城市",
	receiver_district varchar(100) not null default "unknow" comment "收货人的所在地区",
	receiver_town varchar(300) not null default "unknow" comment "收货人街道地址",
	receiver_address varchar(900) not null default "unknow" comment "收货人详细地址",
	receiver_zip int not null default 000000 comment "收货人的邮编",
	receiver_mobile varchar(300) not null default "000000" comment "收货人的手机号码",
	receiver_phone varchar(300) not null default "000000" comment "收货人的电话号码",
	seller_flag int not null default 0 comment "卖家备注旗帜",
	has_buyer_message char(10) not null default "unknow" comment "判断订单是否有买家留言",
	trade_from varchar(100) not null default "unknow" comment "交易内部来源",
	step_trade_status varchar(300) not null default "unknow" comment "分阶段付款的订单",
	step_paid_fee decimal(9,2) not null default -1.00 comment "分阶段付款的已付金额",
	trade_source varchar(900) not null default "unknow" comment "交易外部来源",
	send_time date not null default "0000-00-00" comment "订单将在此时间前发出",
	seller_can_rate char(10) not null default "unknow" comment "卖家是否对订单进行评价",
	order_title varchar(1200) not null default "unknow" comment "商品标题",
	order_pic_path varchar(300) not null default "unknow" comment "商品图片的绝对路径",
	order_price decimal(9,2) not null default -1.00 comment "商品价格",
	order_num_iid varchar(900) not null default "000000" comment "商品数字ID",
	sku_id varchar(300) not null default "000000" comment "商品的最小库存单位Sku的id",
	outer_iid varchar(300) not null default "000000" comment "商家外部编码",
	outer_sku_id varchar(300) not null default "000000" comment "外部网店自己定义的Sku编号",
	refund_status varchar(100) not null default "unknow" comment "退款状态",
	order_status varchar(100) not null default "unknow" comment "订单状态",
	oid varchar(900) not null default "000000" comment "子订单编号",
	order_total_fee decimal(9,2) not null default -1.00 comment "应付金额",
	order_payment decimal(9,2) not null default -1.00 comment "子订单实付金额",
	order_discount_fee decimal(9,2) not null default -1.00 comment "子订单级订单优惠金额",
	order_adjust_fee decimal(9,2) not null default -1.00 comment "手工调整金额",
	divide_order_fee decimal(9,2) not null default -1.00 comment "分摊之后的实付金额",
	part_mjz_discount decimal(9,2) not null default -1.00 comment "优惠分摊",
	sku_properties_name varchar(600) not null default "unknow" comment "sku的值",
	item_meal_id bigint(30) not null default 000000 comment "套餐id",
	item_meal_name  varchar(300) not null default "unknow" comment "套餐的值",
	order_num int  not null default 0 comment "购买数量",
	order_buyer_rate char(10) not null default "unknow" comment "买家是否已评价",
	order_seller_rate char(10) not null default "unknow" comment "卖家是否已评价",
	refund_id bigint(30) not null default 000000 comment "最近退款ID",
	seller_type char(10) not null default "X" comment "卖家类型",
	cid bigint(30) not null default 000000 comment "交易商品对应的类目ID",
	order_end_time datetime not null default "0000-00-00 00:00:00" comment "子订单的交易结束时间",
	order_consign_time datetime not null default "0000-00-00 00:00:00" comment "子订单发货时间",
	order_shipping_type varchar(50) not null default "unknow" comment "子订单的运送方式",
	logistics_company varchar(100) not null default "unknow" comment "子订单发货的快递公司名称",
	invoice_no bigint(30) not null default 000000 comment "子订单所在的包裹的运单号"  ,
	order_tax_fee varchar(50) not null default "0" comment "天猫国际官网直供主订单关税税费",
	credit_card_fee decimal(9,2) not null default -1.0 comment "使用信用卡支付金额",
	mark_desc varchar(900) comment "订单出现异常时，给予用户的描述",
	buyer_open_uid varchar(300) not null default "unknow" comment "买家OpenUid",
	acookie_id varchar(300) not null default "unknow" comment "Acookie订单唯一ID",
	cod_fee decimal(9,2) not null default -1.00 comment "货到付款的服务费",
	code_status varchar(100) not null default "unknow" comment "货到付款的物流状态",
	store_code varchar(300) not null default "unknow" comment "发货的仓库编码",
	sign_time datetime not null default "0000-00-00 00:00:00" comment "签收时间",
	load_date timestamp not null default current_timestamp() comment "下载时间",
	update_date timestamp not null default current_timestamp() comment "更新时间",
	key `tid`  (`tid`) using btree
) engine=InnoDB  default charset=utf8mb4 COMMENT = '订单';



-- ALTER TABLE wms.orders
-- ADD store varchar(150) not null default "unknow" comment "店铺名称"



-- ALTER TABLE wms.orders
-- ADD distributor varchar(150) not null default "unknow" comment "分销店铺名称"